-- ## create_views.sql ##

use [IZVRSITELJSKA_KUCA]
go
create view V_DUGOVANJA
as
select d.ID, d.LICE_ID, i.IME_VEZE, d.SUMA_DUGOVANJA, d.DATUM_UNOSA, d.ROK_ISPLATE, d.RAZLOG
from T_DUGOVANJA d
join T_IZVRSITELJSKE_KUCE i on d.IZVRSITELJSKA_KUCA_ID = i.ID and i.STATUS <> 99
where d.STATUS <> 99;
go
create view V_GRUPE_ORG_JEDINICA
as
select g.ID, g.IME_GRUPE, g.DATUM_DODAVANJA, g.PRIORITET, g.DODATNE_INFORMACIJE
from T_GRUPE_ORG_JEDINICA g
where g.STATUS <> 99;
go
create view V_IZVR_KUCA_GRUPE
as
select i.ID, i.IZVRSITELJSKA_KUCA_ID, z.IME_VEZE, i.GRUPA_ORG_JEDINICE_ID, g.IME_GRUPE, i.INFORMACIJE_VEZE
from T_IZVR_KUCA_GRUPE i
join T_IZVRSITELJSKE_KUCE z on z.ID = i.IZVRSITELJSKA_KUCA_ID and z.STATUS <> 99
join T_GRUPE_ORG_JEDINICA g on g.ID = i.GRUPA_ORG_JEDINICE_ID and g.STATUS <> 99
where i.STATUS <> 99;
go
create view V_IZVRSITELJI
as
select i.ID, i.IME, i.PREZIME, i.SIFRA_UGOVORA, i.PLATA, i.DATUM_ZAPOSLJAVANJA, i.TIP_IZVRSITELJA_ID, t.IME_TIPA
from T_IZVRSITELJI i
join T_TIPOVI_IZVRSITELJA t on t.ID = i.TIP_IZVRSITELJA_ID and t.STATUS <> 99
where i.STATUS <> 99;
go
create view V_IZVRSITELJSKE_KUCE
as
select i.ID, i.IME_VEZE, i.TRAJE_DO, i.DATUM_DODAVANJA, i.LICE_ODOBRILO, i.LICE_ID, l.IME, l.PREZIME,
	i.ORGANIZACIONA_JEDINICA_ID, i.IZVRSITELJ_ID
from T_IZVRSITELJSKE_KUCE i
join T_LICA l on l.ID = i.LICE_ID and l.STATUS <> 99
join T_ORGANIZACIONE_JEDINICE o on o.ID = i.ORGANIZACIONA_JEDINICA_ID and o.STATUS <> 99
join T_IZVRSITELJI z on z.ID = i.IZVRSITELJ_ID and z.STATUS <> 99
where i.STATUS <> 99;
go
create view V_LICA
as
select l.ID, l.IME, l.PREZIME, l.DATUM_RODJENJA, l.JMBG, l.ADRESA_STANOVANJA, l.DODATNE_INFORMACIJE,
	l.DATUM_DODAVANJA
from T_LICA l
where l.STATUS <> 99;
go
create view V_ORG_JED_GRUPE
as
select o.ID, o.ORGANIZACIONA_JEDINICA_ID, r.IME_ORG_JEDINICE, o.GRUPA_ORG_JEDINICE_ID, g.IME_GRUPE,
	o.INFORMACIJE_VEZE
from T_ORG_JED_GRUPE o
join T_ORGANIZACIONE_JEDINICE r on o.ORGANIZACIONA_JEDINICA_ID = r.ID and r.STATUS <> 99
join T_GRUPE_ORG_JEDINICA g on g.ID = o.GRUPA_ORG_JEDINICE_ID and g.STATUS <> 99
where o.STATUS <> 99;
go
create view V_ORGANIZACIONE_JEDINICE
as
select o.ID, o.IME_ORG_JEDINICE, o.KONTAKT_TELEFON, o.FINANSIJSKO_STANJE, o.DATUM_DODAVANJA, o.GLAVNA_LOKACIJA,
	o.EMAIL_ADRESA, o.BROJ_ZAPOSLENIH, o.DODATNE_INFORMACIJE
from T_ORGANIZACIONE_JEDINICE o
where o.STATUS <> 99;
go
create view V_TIPOVI_IZVRSITELJA
as
select t.ID, t.IME_TIPA, t.NAPLATA_USLUGE, t.DODATNE_INFORMACIJE
from T_TIPOVI_IZVRSITELJA t
where t.STATUS <> 99
go
create view V_TRANSAKCIJE
as
select t.ID, t.DUGOVANJE_ID, d.SUMA_DUGOVANJA, t.DATUM_UPLATE, t.UPLATA, t.PORUKA
from T_TRANSAKCIJE t
join T_DUGOVANJA d on d.ID = t.DUGOVANJE_ID and d.STATUS <> 99
where t.STATUS <> 99;
